services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire:                              true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure:                         true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public:                                false

    ## Replaces some Pomm commands to add extra structure informations
    ## as foreign keys, not null, type enum etc...
    Pommx\Console\Command\GenerateEntity:
        class:                                 'Pommx\Console\Command\GenerateEntity'
        tags:                                  ['console.command']
        calls:
            - method:                          'setReplacedCommandClass'
              arguments:
                  - 'PommProject\Cli\Command\GenerateEntity'

    Pommx\Console\Command\GenerateStructure:
        class:                                 Pommx\Console\Command\GenerateStructure
        tags:                                  ['console.command']
        calls:
            - method:                          'setReplacedCommandClass'
              arguments:
                  - 'PommProject\Cli\Command\GenerateRelationStructure'

    Pommx\Console\Command\GenerateRepository:
        class:                                 Pommx\Console\Command\GenerateRepository
        tags:                                  ['console.command']
        calls:
            - method:                          'setReplacedCommandClass'
              arguments:
                  - 'PommProject\Cli\Command\GenerateRelationModel'

    Pommx\Console\Command\GenerateRelation:
        class:                                 Pommx\Console\Command\GenerateRelation
        tags:                                  ['console.command']
        calls:
            - method:                          'setReplacedCommandClass'
              arguments:
                  - 'PommProject\Cli\Command\GenerateForRelation'

    Pommx\Console\Command\GenerateSchema:
        class:                                 Pommx\Console\Command\GenerateSchema
        tags:                                  ['console.command']
        calls:
            - method:                          'setReplacedCommandClass'
              arguments:
                  - 'PommProject\Cli\Command\GenerateForSchema'
