services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire:                               true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure:                          true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public:                                 false

    ## Entity property info
    Pommx\PropertyInfo\Extractor\ListExtractor:
        class:                                  Pommx\PropertyInfo\Extractor\ListExtractor

    ## Decorates default extractors
    Pommx\PropertyInfo\Extractor\TypeExtractor:
        class:                                  Pommx\PropertyInfo\Extractor\TypeExtractor
        decorates:                              'pomm.property_type_info'
        arguments:
            $extractor:                         '@Pommx\PropertyInfo\Extractor\TypeExtractor.inner'

    ## Replaces default extractors
    pomm.property_list_info:                    '@Pommx\PropertyInfo\Extractor\ListExtractor'

    ## Replaces this deprecated service, otherwise its called
    pomm.property_info:                         '@Pommx\PropertyInfo\Extractor\TypeExtractor'
