<?php

/*
 * This file is part of the Pommx package.
 *
 * (c) Safouan MATMATI <safouan.matmati@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Pommx\Bridge\Phinx\Console\Command;

use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

use Phinx\Console\Command\SeedCreate as PhinxSeedCreate;

use Pommx\Bridge\Phinx\Console\Command\Adapter;

use Pommx\Bridge\Phinx\Seed\AbstractSeed;

class SeedCreate extends PhinxSeedCreate
{
    use Adapter;

    /**
     * [execute description]
     * @param  InputInterface  $input  [description]
     * @param  OutputInterface $output [description]
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $section = $output->section();

        // Prepare configurations depending on <config-name> argument
        $this->preExecute($input, $section);

        // Define template depending on 'parent_class' extension option
        $parent_class = $this->getPommxSeedConf()->getValue('parent_class');

        if ($parent_class !== AbstractSeed::class) {
            if (false == $this->hasMethodImplemented('getSchemasNames', $parent_class)) {
                throw new \InvalidArgumentException(
                    sprintf(
                        '"%s" class should implements "%s" method.',
                        $parent_class,
                        'getSchemasNames'
                    )
                );
            }

            $this->useCustomTemplate(true);
        }

        // File is generated by Phinx core
        parent::execute($input, $section);

        // Update it replacing Pommx wildcards
        $path = $this->getSeedPath($input, $output);

        $file_path = realpath($path) . DIRECTORY_SEPARATOR . $input->getArgument('name') . '.php';

        $wildcards = [
            '{$schema}'         => $input->getArgument('schema'),
            '{$base_namespace}' => $parent_class
        ];

        $contents = strtr(file_get_contents($file_path), $wildcards);

        if (file_put_contents($file_path, $contents) === false) {
            throw new \RuntimeException(sprintf(
                'The file "%s" could not be written',
                $file_path
            ));
        }

        $section->overwrite(sprintf('<info>%s seed file created.</info>', $file_path));
    }
}
