services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire:                                                   true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure:                                              true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public:                                                     false

    Pommx\DependencyInjection\Compiler\CommandsPass:
        class:                                                      Pommx\DependencyInjection\Compiler\CommandsPass
        tags:
            - { name: 'pommx.di.pass', priority:                    300 }

    Pommx\DependencyInjection\Compiler\RepositoryClassFinderPass:
        class:                                                      'Pommx\DependencyInjection\Compiler\RepositoryClassFinderPass'
        tags:
            - { name: 'pommx.di.pass', priority:                    200 }


    Pommx\DependencyInjection\Compiler\QueryBuilderExtensionPass:
        class:                                                      Pommx\DependencyInjection\Compiler\QueryBuilderExtensionPass
        tags:
            - { name: 'pommx.di.pass', priority:                    100 }
