services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire:                                                                        true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure:                                                                   true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public:                                                                          false

    Pommx\Bridge\ApiPlatform\Pagination\PaginationExtension:
        class:                                                                           Pommx\Bridge\ApiPlatform\Pagination\PaginationExtension
        arguments:
            - '@Pommx\Repository\Extension\Pagination\Pagination'
            - '@request_stack'
            - '@api_platform.metadata.resource.metadata_factory'
            - '%api_platform.collection.pagination.enabled%'
            - '%api_platform.collection.pagination.client_enabled%'
            - '%api_platform.collection.pagination.client_items_per_page%'
            - '%api_platform.collection.pagination.items_per_page%'
            - '%api_platform.collection.pagination.page_parameter_name%'
            - '%api_platform.collection.pagination.enabled_parameter_name%'
            - '%api_platform.collection.pagination.items_per_page_parameter_name%'
            - '%api_platform.collection.pagination.maximum_items_per_page%'
            - '%api_platform.collection.pagination.partial%'
            - '%api_platform.collection.pagination.client_partial%'
            - '%api_platform.collection.pagination.partial_parameter_name%'

    Pommx\Bridge\ApiPlatform\DataPersister\DataPersister:
        class:                                                                           Pommx\Bridge\ApiPlatform\DataPersister\DataPersister
        tags: [ { name:                                                                  'api_platform.data_persister'} ]

    Pommx\Bridge\ApiPlatform\DataProvider\DataProvider:
        class:                                                                           Pommx\Bridge\ApiPlatform\DataProvider\DataProvider
        tags:
            - { name:                                                                    'api_platform.item_data_provider'}
            - { name:                                                                    'api_platform.collection_data_provider'}
            - { name:                                                                    'api_platform.subresource_data_provider'}

    # Replace Entity Normalizer
    Pommx\Bridge\ApiPlatform\Serializer\EntityNormalizer:
        class:                                                                           Pommx\Bridge\ApiPlatform\Serializer\EntityNormalizer
        tags:                                       [{name: 'serializer.normalizer', priority: 100}]

    # Uses Pomm Structure to define extra metadata (identifier, required etc...)
    Pommx\Bridge\ApiPlatform\Metadata\Property\Factory\StructurePropertyMetadataFactory:
      class:                                                                             Pommx\Bridge\ApiPlatform\Metadata\Property\Factory\StructurePropertyMetadataFactory
      decorates:                                                                         'api_platform.metadata.property.metadata_factory'
      arguments:
          $decorated:                                                                    '@Pommx\Bridge\ApiPlatform\Metadata\Property\Factory\StructurePropertyMetadataFactory.inner'
      decoration_priority:                                                               500
